inherit_gem:
  bixby: bixby_default.yml

inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'spec/test_app_templates/**/*.rb'

# engine_cart
Bundler/DuplicatedGem:
  Exclude:
    - 'Gemfile'

# engine_cart
Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

RSpec/ExampleLength:
  Exclude:
    - 'spec/**/*.rb'

# By default RSpec/MessageSpies has the following:
# Prefer have_received for setting message expectations. Setup form as a spy using allow or instance_spy.
# The default assumes EnforcedStyle is 'have_received'. Most of our specs are 'receive'
RSpec/MessageSpies:
  Enabled: false
